global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  
        labels:
          tier: infrastructure
  
  - job_name: 'fulfilment-processor'
    static_configs:
      - targets: ['fulfilment-processor-1:9110','fulfilment-processor-2:9110','fulfilment-processor-3:9110']
        labels:
          tier: backend
      
  - job_name: 'fulfilment-api'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['fulfilment-api']
        labels:
          tier: web