version: '3.7'

services:

  node-exporter:
    image: courselabs/node-exporter
    networks: 
      - metrics

  fulfilment-api:
    image: courselabs/fulfilment-api
    ports:
      - 8080:80
    networks: 
      - fulfilment
      - metrics

  fulfilment-processor-1:
    image: courselabs/fulfilment-processor
    environment:
      - Observability__Metrics__IncludeRuntime=true
      - Observability__StartupDelaySeconds=20
      - Observability__ExitAfterSeconds=90
    restart: always
    networks: 
      - fulfilment
      - metrics

  fulfilment-processor-2:
    image: courselabs/fulfilment-processor
    environment:
      - Observability__Metrics__IncludeRuntime=true
      - Observability__Metrics__Factor=3
    networks: 
      - fulfilment
      - metrics

  fulfilment-processor-3:
    image: courselabs/fulfilment-processor
    environment:
      - Observability__Metrics__IncludeRuntime=true
      - Observability__Metrics__Factor=0.5
      - Observability__Metrics__FailureFactor=0.3
      - Observability__Metrics__AppVersion=1.5.2
    networks: 
      - fulfilment
      - metrics

networks: 
  fulfilment:
  metrics:
    name: metrics
