version: '3.7'

services:

  prometheus:
    image: courselabs/prometheus:v2.28.1
    ports: 
      - 9091:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics

  grafana:
    image: courselabs/grafana:8.0.5
    ports: 
      - 3001:3000
    networks:
      - metrics

networks: 
  metrics:
    name: metrics